### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by amalloy**
Improved vocabulary???

### CODE REVIEW

**Comment by gfredericks** [comment]
I agree with the "???" part. I can't judge the difference between these two words and would like a third opinion.

**Comment by amalloy** [comment]
@noisesmith please we need your help.

**Comment by noisesmith** [comment]
Obtainance, Preobtaininations

**Comment by gfredericks** [comment]
obtention?

**Comment by noisesmith** [comment]
I vote for obtention, bonus points for being a real word

**Comment by amalloy** [comment]
Seconded. Motion carried.

**Comment by gfredericks** [comment]
I didn't even know it was a real word; it just made intuitive sense I think because of "obtener" from spanish.

**Comment by gfredericks** [comment]
now I move on to the arduous task of applying this change to all my other repos :/

**Comment by amalloy** [comment]
Just make them all include this one by reference.

**Pull request merged**
